name: First github action ever created
run-name: ${{ github.actor }} is testing github actions 🚀
on: [push]
jobs:
  my-first-job: 
    runs-on: ubuntu-latest
    steps: 
    
     - name: greeting
       env: 
         DEFAULT_GREETING_FIRST: Hi, my name is
         FIRST_NAME: John Doe
       run: |
          echo $DEFAULT_GREETING_FIRST, $FIRST_NAME!
          
     - name: show directory
       run: ls -l
 
  my-second-job: 
    runs-on: ubuntu-latest
    steps: 
     - name: show current directory
       run: pwd
       
  Echo-Text-To-Terminal: 
    runs-on: ubuntu-latest
    needs: [my-first-job,my-second-job]
    steps: 
      - run: echo "The job was automatically triggered by ${{ github.actor }}"
      - run: echo "The job is running on ${{ runner.os }}"
      - run: echo "The name of the branch is ${{ github.ref_name }}"
      
      - name: check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} has been cloned to the runner"
      - run: echo "The workflow is now ready to test your code on the runner"
      
      - name: List files in repository
        run: ls ${{ github.workspace }} 
      - run: echo "This job status is ${{ job.status }}"

